FROM python:3.12-slim AS builder
COPY requirements.txt /tmp/requirements.txt
RUN pip install --user --no-cache-dir -r /tmp/requirements.txt

FROM python:3.12-slim
COPY --from=builder /root/.local /root/.local
ENV PATH=/root/.local/bin:$PATH
WORKDIR /app
COPY vigie/ /app/vigie/

RUN python -m compileall -b /app/vigie && \
    find /app/vigie -name "*.py" -delete

CMD ["python", "-m", "vigie"]
