user nginx;
worker_processes auto;
pid /run/nginx.pid;

load_module modules/ngx_http_geoip2_module.so;

events { worker_connections 1024; }

http {
    sendfile on;
    server_tokens off;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format c2 '$remote_addr [$time_local] "$request" $status "$http_user_agent" $geoip2_data_country_iso_code';
    access_log /var/log/nginx/access.log c2;
    error_log  /var/log/nginx/error.log warn;

    geoip2 /usr/share/GeoIP/GeoLite2-Country.mmdb {
        auto_reload 5m;
        $geoip2_data_country_iso_code country iso_code;
    }

    map $geoip2_data_country_iso_code $allowed_country {
        default 0;
        FR 1; DE 1; BE 1; NL 1; IT 1; ES 1; GB 1;
        CH 1; AT 1; PL 1; SE 1; NO 1; DK 1; FI 1;
        PT 1; CZ 1; RO 1; HU 1; IE 1; LU 1; SK 1;
        "" 1;
    }

    map $http_user_agent $blocked_ua {
        default      0;
        "~*curl"     1; "~*python"     1; "~*perl"   1;
        "~*nmap"     1; "~*masscan"    1; "~*zgrab"  1;
        "~*shodan"   1; "~*censys"     1; "~*nuclei" 1;
        "~*nikto"    1; "~*sqlmap"     1; "~*ffuf"   1;
        "~*gobuster" 1; "~*feroxbuster" 1;
        ""           1;
    }

    include /etc/nginx/conf.d/*.conf;
}
