FROM shenxn/protonmail-bridge:latest

RUN apt-get update && \
    apt-get install -y --no-install-recommends libfido2-1 expect && \
    rm -rf /var/lib/apt/lists/*

COPY entrypoint-protonmail.sh /protonmail/entrypoint.sh
RUN chmod +x /protonmail/entrypoint.sh
