volumes:
  data_logs:
  data_cache:
configs:
  provisioning_env:
    file: /opt/bojemoi/volumes/provisioning/.env

services:
  orchestrator:
    image: localhost:5000/provisioning:latest
    hostname: orchestrator.bojemoi.lab
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 --app-dir /app
    ports:
      - "28080:8080"
#    configs:
#      - source: provisioning_env
#        target: /app/.env
#        mode: 0440
    volumes:
      # Socket Docker pour piloter les containers
      - /var/run/docker.sock:/var/run/docker.sock
      # Logs persistants
      - data_logs:/app/logs
      # Cache
      - data_cache:/app/cache
    networks:
      - backend 
      - proxy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:                                                                            
      replicas: 1                                                                      
      placement:                                                                       
        constraints:                                                                   
          - node.role == manager                                                       
      restart_policy:                                                                  
        condition: on-failure                                                          
        delay: 5s                                                                      
        max_attempts: 3                                                                
      resources:                                                                       
        limits:                                                                        
          memory: 512M                                                                 
        reservations:                                                                  
          memory: 256M                                                                 
      labels:                                                                          
        - "bojemoi.service=orchestrator"
        - "bojemoi.environment=production"
        - prometheus.port=5000                                                         
        - prometheus.path=/metrics                                                     
        - prometheus.label.team=infrastructure 
        - prometheus.label.component=provisioning 
        - prometheus.label.stack=base                                                  
        - prometheus.label.tier=data             
        
        # Labels Prometheus
        - "prometheus.scrape=true"
        - "prometheus.port=9090"
        
        # Traefik - Configuration générale
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        
        # Traefik - API HTTP (port 8080)
        - "traefik.http.routers.orchestrator-api.rule=Host(`provisioning.bojemoi.lab`)"
        - "traefik.http.routers.orchestrator-api.entrypoints=websecure"
        - "traefik.http.routers.orchestrator-api.tls=true"
        - "traefik.http.routers.orchestrator-api.tls.certresolver=letsencrypt"
        - "traefik.http.routers.orchestrator-api.service=orchestrator-api"
        - "traefik.http.services.orchestrator-api.loadbalancer.server.port=8080"
        
        # Traefik - Webhook endpoint avec rate limiting
        - "traefik.http.routers.orchestrator-webhook.rule=Host(`provisioning.bojemoi.lab`) && PathPrefix(`/webhook`)"
        - "traefik.http.routers.orchestrator-webhook.entrypoints=websecure"
        - "traefik.http.routers.orchestrator-webhook.tls=true"
        - "traefik.http.routers.orchestrator-webhook.middlewares=orchestrator-ratelimit"
        - "traefik.http.middlewares.orchestrator-ratelimit.ratelimit.average=10"
        - "traefik.http.middlewares.orchestrator-ratelimit.ratelimit.burst=20"
        
        # Traefik - Metrics Prometheus 
        - "traefik.http.routers.orchestrator-metrics.rule=Host(`provisioning.bojemoi.lab`) && PathPrefix(`/metrics`)"
        - "traefik.http.routers.orchestrator-metrics.entrypoints=websecure"
        - "traefik.http.routers.orchestrator-metrics.tls=true"
        - "traefik.http.routers.orchestrator-metrics.service=orchestrator-metrics"
        - "traefik.http.services.orchestrator-metrics.loadbalancer.server.port=8080"
        
        # Traefik - Health check
        - "traefik.http.routers.orchestrator-health.rule=Host(`provisioning.bojemoi.lab`) && PathPrefix(`/health`)"
        - "traefik.http.routers.orchestrator-health.entrypoints=websecure"
        - "traefik.http.routers.orchestrator-health.tls=true"


networks:
  backend:
    external: true
  proxy:
    external: true


