volumes:
  zap-data:
    driver: local
  scan_results:
    driver: local
  scan_logs:
    driver: local
  zap-reports:
    driver: local
    name: zap
  zap-scripts:
    driver: local
    name: zap 

networks:
  backend:
    external: true
  proxy:
    external: true

services:
  zaproxy:
    image: localhost:5000/oblast:latest
    hostname: zaproxy
    networks:
      - backend
      - proxy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.zap.rule=Host(`zap.bojemoi.lab`)"
        - "traefik.http.routers.zap.entrypoints=websecure"
#        - "traefik.http.routers.zap.tls.certresolver=letsencrypt"
        - "traefik.http.routers.zap.middlewares=security-headers,vpn-whitelist"
        - "traefik.http.services.zap.loadbalancer.server.port=8090"
      replicas: 1
      placement:
        constraints:
           - node.role == worker
      restart_policy:
        condition: on-failure
        max_attempts: 3
    command: >
      -daemon -host 0.0.0.0 -port 8090
      -config api.addrs.addr.name=.*
      -config api.addrs.addr.regex=true
      -config api.disablekey=true

  # Scanner ZAP (notre application)
  zap-scanner:
    image: localhost:5000/oblast-1:latest
    hostname: zap_scanner
    environment:
      # Configuration base de données
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: msf
      DB_USER: postgres
      DB_PASSWORD: bojemoi
      
      # Configuration ZAP
      ZAP_HOST: zaproxy
      ZAP_PORT: 8090
      ZAP_API_KEY: ""
      
      # Configuration logging
      PYTHONUNBUFFERED: 1
      LOG_LEVEL: INFO
    volumes:
      - scan_results:/results
      - scan_logs:/logs
    networks:
      - backend
    # Optionnel: démarrage différé pour s'assurer que tous les services sont prêts
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      placement:
        constraints:
           - node.role == worker
        max_replicas_per_node: 3


