services:
  nuclei:
    image: localhost:5000/nuclei:latest
    networks:
      - pentest 
    volumes:
      - nuclei-templates:/root/nuclei-templates
      - nuclei-output:/output
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: '2'
          memory: 2G
    command: ["sleep", "infinity"]  # Keep container running
    labels:
      - "com.bojemoi.service=nuclei"

volumes:
  nuclei-templates:
  nuclei-output:

networks:
  pentest:
    external: true

