# Bojemoi Lab - ML Threat Intelligence Stack
# IoC analysis with ML classification and OSINT integration

x-deploy-template: &deploy-template
  placement:
    constraints:
      - node.role == worker
  restart_policy:
    condition: on-failure
    delay: 5s
    max_attempts: 3
  update_config:
    parallelism: 1
    delay: 10s
    failure_action: rollback
  resources:
    limits:
      cpus: '1.0'
      memory: 1G
    reservations:
      cpus: '0.25'
      memory: 512M

networks:
  backend:
    external: true
  proxy:
    external: true

volumes:
  ml-threat-intel-models:
    driver: local

services:
  # ML Threat Intelligence API
  ml-threat-intel-api:
    image: localhost:5000/ml-threat-intel:latest
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: bojemoi_threat_intel
      DB_USER: postgres
      DB_PASSWORD: bojemoi
      VT_API_KEY_FILE: /run/secrets/vt_api_key
      ABUSEIPDB_API_KEY_FILE: /run/secrets/abuseipdb_api_key
      OTX_API_KEY_FILE: /run/secrets/otx_api_key
      SHODAN_API_KEY_FILE: /run/secrets/shodan_api_key
      ANTHROPIC_API_KEY_FILE: /run/secrets/anthropic_api_key
    volumes:
      - ml-threat-intel-models:/app/models
      - /opt/bojemoi-ml-threat/config:/app/config:ro
    networks:
      - backend
      - proxy
    secrets:
      - vt_api_key
      - abuseipdb_api_key
      - otx_api_key
      - shodan_api_key
      - anthropic_api_key
    deploy:
      <<: *deploy-template
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.ml-threat-intel.rule=Host(`threat-intel.bojemoi.lab.local`)"
        - "traefik.http.routers.ml-threat-intel.entrypoints=web"
        - "traefik.http.services.ml-threat-intel.loadbalancer.server.port=8001"

secrets:
  vt_api_key:
    external: true
  abuseipdb_api_key:
    external: true
  otx_api_key:
    external: true
  shodan_api_key:
    external: true
  anthropic_api_key:
    external: true
