# Razvedka - CTI / DDoS Prediction Service
# Monitors Telegram + X/Twitter hacktivist channels for DDoS buzz targeting France
# Extracts entities, scores intent, alerts on cluster detection

networks:
  backend:
    external: true

volumes:
  razvedka-session:
    driver: local

secrets:
  telegram_api_id:
    external: true
  telegram_api_hash:
    external: true
  telegram_phone:
    external: true
  telegram_bot_token:
    external: true
  telegram_alert_chat_id:
    external: true
  # twitter_bearer_token:  # uncomment after: docker secret create twitter_bearer_token -
  #   external: true

services:
  razvedka:
    image: localhost:5000/razvedka:latest
    hostname: razvedka
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: bojemoi
      PG_DATABASE: razvedka
      TELEGRAM_CHANNELS: >-
        ddos_separ,
        RVvoenkor,
        CyberArmyofRussia,
        killnet_info,
        XakNet_Team,
        SolntsepekZ,
        russian_hackers_team
      BUZZ_CHECK_INTERVAL: "60"
      ALERT_CHANNEL_THRESHOLD: "3"
      ALERT_MENTION_THRESHOLD: "5"
      ALERTMANAGER_WEBHOOK_URL: "http://alertmanager:9093/api/v1/alerts"
      METRICS_PORT: "9300"
      TWITTER_ACCOUNTS: >-
        CyberArmyRussia_,
        killnet_reserv,
        XakNet_Team,
        SolntsepekZ,
        russian_hackers_team,
        ddos_separ,
        RVvoenkor
      TWITTER_SEARCH_QUERIES: "ddos france lang:ru|ддос франция|ddos .fr"
      TWITTER_POLL_INTERVAL: "90"
    secrets:
      - telegram_api_id
      - telegram_api_hash
      - telegram_phone
      - telegram_bot_token
      - telegram_alert_chat_id
      # - twitter_bearer_token  # uncomment after creating the secret
    volumes:
      - razvedka-session:/data
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
      resources:
        limits:
          cpus: '1'
          memory: 768M
        reservations:
          cpus: '0.1'
          memory: 256M
      labels:
        - "prometheus.enable=true"
        - "prometheus.port=9300"
        - "prometheus.path=/metrics"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:9300/metrics')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
