networks:
  backend:
    external: true

services:
  dozor:
    image: localhost:5000/dozor:latest
    environment:
      POLL_INTERVAL: "3600"
      RULES_OUTPUT_PATH: "/var/lib/suricata/rules/blocklist.rules"
      SURICATA_SOCKET_PATH: "/var/run/suricata/suricata-command.socket"
      METRICS_PORT: "9302"
    volumes:
      - /opt/bojemoi/volumes/suricata/rules:/var/lib/suricata/rules
      - /opt/bojemoi/volumes/suricata/run:/var/run/suricata
    networks:
      - backend
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.05'
          memory: 64M
      labels:
        - "prometheus.enable=true"
        - "prometheus.port=9302"
        - "prometheus.path=/metrics"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:9302/metrics')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  eve-cleaner:
    image: localhost:5000/alpine:latest
    volumes:
      - /opt/bojemoi/volumes/suricata/logs:/var/log/suricata
    environment:
      KEEP_HOURS: "24"
    command: >
      sh -c "while true; do
        find /var/log/suricata -name 'eve.*.json' -mmin +$$((KEEP_HOURS * 60)) -delete 2>/dev/null;
        echo \"[eve-cleaner] cleaned eve logs older than $${KEEP_HOURS}h\";
        sleep 3600;
      done"
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "1"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '0.05'
          memory: 32M
        reservations:
          cpus: '0.01'
          memory: 8M
