networks:
  backend:
    external: true
  pentest:
    external: true

volumes:
  vulnx-results:
    driver: local

services:
  vulnx:
    image: python:3.11-slim
    networks:
      - backend
      - pentest
    volumes:
      - vulnx-results:/results
      - /opt/bojemoi/samsonov/vulnx_wrapper:/app
    working_dir: /app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RESULTS_DIR=/results
    command: >
      sh -c "apt-get update && apt-get install -y git &&
             pip install requests colorama redis --break-system-packages &&
             git clone https://github.com/anouarbensaad/vulnx.git /opt/vulnx 2>/dev/null || true &&
             pip install -r /opt/vulnx/requirements.txt --break-system-packages || true &&
             python main.py --daemon"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
