networks:
  backend:
    external: true
  proxy:
    external: true
  pentest:
    external: true
volumes:
  faraday_data:
    driver: local
  redis_data:
    driver: local
  faraday-storage:
    driver: local
configs:
  faraday-server_config:
    file: /opt/bojemoi/volumes/faraday/config/server.ini
services:
#==================================
#
#==================================
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes --protected-mode no
#--requirepass ${FARADAY_REDIS_PASSWORD:-faraday_redis_pass}
    networks:
      - pentest
      - backend
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3



#==================================
#
#=================================
  orchestrator:
    image: python:3.11-slim
    volumes:
      - /opt/bojemoi/samsonov/pentest_orchestrator:/app
    working_dir: /app
    command: python main.py
    networks:
      - pentest
      - backend
    dns_search:
      - bojemoi.lab
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
#==================================
#
#=================================
  faraday:
    image:  faradaysec/faraday:latest
    environment:
      - PGSQL_USER=postgres
      - PGSQL_PASSWD=bojemoi
      - PGSQL_HOST=postgres
      - PGSQL_DBNAME=faraday
      - REDIS_SERVER=redis.bojemoi.lab
      - REDIS_PORT=6379
      - REDIS_HOST=redis  # ou le nom de votre service Redis
      - REDIS_DB=0

    networks:
      - proxy
      - backend
      - pentest
    dns_search:
      - bojemoi.lab
    ports:
      - 5985:5985
    configs:
      - source: faraday-server_config
        target: /home/faraday/.faraday/config/server.ini
    volumes:
      - faraday_data:/home/faraday/.faraday
      - faraday-storage:/home/faraday/.faraday/storage
      - /opt/bojemoi/volumes/faraday/config/server.ini:/home/faraday/.faraday/config/server.ini
    entrypoint: "/entrypoint.sh"
#    restart: always
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.faraday.rule=Host(`faraday.bojemoi.lab`)
        - traefik.http.routers.faraday.entrypoints=websecure
        - traefik.http.routers.faraday.tls=true
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.faraday.tls.certresolver=letsencrypt"
        - "traefik.http.services.faraday.loadbalancer.server.port=5985"
        
      replicas: 1
      placement:
          constraints:
            - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
#    command: sh -c "tail -f /dev/null"

#==================================
#
#=================================

  redis-exporter:
    image: oliver006/redis_exporter:latest
    environment:
      REDIS_ADDR: "redis:6379"
      REDIS_PASSWORD: "${REDIS_PASSWORD:-}"
    networks:
      - pentest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 64M
      placement:
          constraints:
            - node.role == manager
#==================================
#
#=================================
  pentest-exporter:
    image: python:latest
    command: >
        sh -c "pip3 install  prometheus_client requests redis &&
           python3 /app/metrics_exporter.py"


    volumes:
      - /opt/bojemoi/samsonov/scripts/metrics_exporter.py:/app/metrics_exporter.py
    networks:
      - pentest
    deploy:
      labels:
        - "prometheus.scrape=true"
#        - "prometheus.port=9999"
      placement:
          constraints:
            - node.role == manager

