#--------------------------------------------------------------------------------
# for base  images
# -------------------------------------------------------------------------------
networks:
  monitoring:
    name: monitoring
    driver: overlay
    attachable: true
  backend:
    name: backend
    attachable: true
  frontend:
    name: frontend
    driver: overlay
    attachable: true
  rsync_network:
    name: rsync_network
    driver: overlay
    attachable: true
volumes:
  postgres_data:
    external: true
    name: bojemoi
  registry_data:
    external: true
    name: registry
  grafana_data:
    driver: local
  prometheus_data:
    name: prometheus_data
    external: true
  loki_data:
    driver: local
  rsync_logs:
    driver: local
  alertmanager_data: 
  elasticsearch_data:
  ssh_keys:
    driver: local  
  rsync_logs:
    driver: local
  postfix_data:
    driver: local

secrets:
  rsync_config:
    file: /opt/bojemoi/volumes/rsync/configs/rsyncd.conf
  ssh_private_key:
    file: /opt/bojemoi/volumes/rsync/ssh-keys/id_rsa
                                                                             
# Template de base avec anchor                                                   
x-mode-template: &mode-template                                             
  image: localhost:5000/koursk:latest
  networks:                          
    -  backend                       
  depends_on:                        
    - postgres                     
# Template de d..ploiement s..par..
x-deploy-template: &deploy-template
    placement:                     
      max_replicas_per_node: 1     
    restart_policy:                
      condition: on-failure   
      delay: 5s               
      max_attempts: 3         
    update_config:                                   
      parallelism: 1                                 
      delay: 10s                                     
      failure_action: rollback                       
    resources:                                       
      limits:                                        
        cpus: '0.1'                                     
        memory: 512M                                    
      reservations:                                     
        cpus: '0.1'                                     
        memory: 100M                                    
                           

services:
  # =========================================================================
  # SERVICE:  registry 
  # ========================================================================
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
      - registry_data:/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # =========================================================================
  # SERVICE:  postgres
  # =========================================================================

  postgres:
    image: postgres:17 
    environment:
      POSTGRES_PASSWORD: bojemoi 
      POSTGRES_USER: postgres 
      POSTGRES_DB: msf 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    ports:
      - "5432:5432"
    networks:
      -  backend
    restart: unless-stopped



  # =========================================================================
  # SERVICE: suricata 
  # =========================================================================
  suricata:
    image: jasonish/suricata:latest
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - NET_RAW
    environment:
      - SURICATA_OPTIONS=-i eth0 --set stream.reassembly.depth=0 --set detect.profile=low
    restart: unless-stopped

  # =========================================================================
  # SERVICE: Grafana (Serveur principal de visualisation)
  # =========================================================================
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    networks:
      - monitoring
      - backend
    ports:
      - "3000:3000"
    environment:
      GF_SERVER_ROOT_URL: http://localhost:3000
      GF_SECURITY_ADMIN_PASSWORD: admin_password
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: postgres:5432
      GF_DATABASE_NAME: grafana
      GF_DATABASE_USER: postgres
      GF_DATABASE_PASSWORD: bojemoi 
      GF_DATABASE_SSL_MODE: disable
    volumes:
      - grafana_data:/var/lib/grafana
#      - /opt/bojemoi/volumes/grafana:/var/lib/grafana
      - /opt/bojemoi/volumes/grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - postgres 
      - loki
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  # =========================================================================
  # SERVICE: Prometheus (Collecte et stockage de métriques)
  # =========================================================================
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    networks:
      - monitoring
      - rsync_network
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.enable-lifecycle
    volumes:
      - prometheus_data:/prometheus
      - /opt/bojemoi/volumes/prometheus:/etc/prometheus:ro
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.role == manager


  # =========================================================================
  # SERVICE: Loki (Agrégation et stockage de logs)
  # =========================================================================
  loki:
    image: grafana/loki:latest
    restart: unless-stopped
    networks:
      - monitoring
    ports:
      - "3100:3100"
    command:
      -  -config.file=/etc/loki/local-config.yml
      -  -config.expand-env=true 
    volumes:
      - /opt/bojemoi/volumes/grafana/loki/loki-config.yml:/etc/loki/local-config.yml:ro

      - loki_data:/loki
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.role == manager
  # =========================================================================
  # =========================================================================
  alloy:
    image: grafana/alloy:latest
    ports:
      - "12345:12345"
    volumes:
      - ./alloy-config.alloy:/etc/alloy/config.alloy
      - /var/log:/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - rsync_logs:/rsync/logs
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
    networks:
      - monitoring
    restart: unless-stopped
    depends_on:
      - prometheus
      - loki
##############
  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "9093:9093"
    volumes:
#      - /opt/bojemoi/volumes/monitoring/alertmanager/templates/default.tmpl:/etc/alertmanager/templates/default.tmpl:ro
      - /opt/bojemoi/volumes/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=http://localhost:9093/'
    restart: unless-stopped
    networks:
      - monitoring
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.role == manager
  # =========================================================================
  # =========================================================================

  node-exporter:
    image: prom/node-exporter:latest
    hostname: "{{.Node.Hostname}}"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    networks:
      - monitoring
    deploy:
      mode: global  # Clé importante : déploie une instance sur chaque node
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  # =============================================================================
  # SERVEUR SMTP PRODUCTION (Postfix)
  # =============================================================================
  postfix:
    image: boky/postfix:latest
    environment:
      ALLOWED_SENDER_DOMAINS: "bojemoi.me"
      HOSTNAME: "mail.example.com"
    ports:
      - "25:25"
    networks:
      - monitoring
    volumes:
      - postfix_data:/var/spool/postfix
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "prometheus.enable=false"
  # =========================================================================
  # =========================================================================

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs
      - /var/run:/var/run
      - /sys:/sys
      - /var/lib/docker/:/var/lib/docker
      - /dev/disk/:/dev/disk
#    privileged: true
#    devices:
#	      - /dev/kmsg
    restart: unless-stopped
    networks:
      - monitoring
  # =========================================================================
  # =========================================================================

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    restart: unless-stopped
    networks:
      - monitoring
  # =========================================================================
  # =========================================================================

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    restart: unless-stopped
    networks:
      - monitoring
  # =========================================================================
  # =========================================================================

  logstash:
    image: docker.elastic.co/logstash/logstash:8.8.0
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - /opt/bojemoi/volumes/monitoring/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - /opt/bojemoi/volumes/monitoring/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    depends_on:
      - elasticsearch
    restart: unless-stopped
    networks:
      - monitoring


#--------------------------------------------------------------------------------
# for base  images
# -------------------------------------------------------------------------------



  # =========================================================================
  # SERVICE:  rsync 
  # ========================================================================

  rsync-master:
    <<: *mode-template  # H..rite du template de base
    image: localhost:5000/koursk-2:latest
    hostname: rsync-master
    ports:
       - "8080:8080"
    deploy:
      <<: *deploy-template  # H..rite du template de d..
      replicas: 1 
      placement:
        constraints:
          - node.role == manager
    volumes:
       - type: bind
         source: /opt/bojemoi
         target: /opt/bojemoi
       - ssh_keys:/root/.ssh:ro
       - rsync_logs:/var/log/rsync
       - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
             - MODULE=swarm_data
             - DATA_PATH=/opt/bojemoi
             - RSYNC_MODE=master
             - SYNC_INTERVAL=300
             - REMOTE_HOSTS=rsync-slave
    networks:
       - rsync_network
    command: ["/scripts/rsync-start.sh"]



  rsync-slave:
    <<: *mode-template  # H..rite du template de base
    hostname: rsync-slave
    deploy:
      <<: *deploy-template  # H..rite du template de d..
      replicas: 3
      placement:
        preferences:
          - spread: node.id
      update_config:
        parallelism: 1
        delay: 10s
    volumes:
      - type: bind
        source: /opt/bojemoi
        target: /opt/bojemoi
      - ssh_keys:/root/.ssh
      - rsync_logs:/var/log/rsync
    environment:
      - RSYNC_MODE=slave
      - MASTER_HOST=rsync-master
      - DATA_PATH=/opt/bojemoi
    networks:
      - rsync_network
    command: ["/scripts/rsync-slave.sh"]


