#--------------------------------------------------------------------------------
# for base  images
# -------------------------------------------------------------------------------
networks:
  rsync_network:
    name: rsync_network
    driver: overlay
    attachable: true
  monitoring:
     external: true

volumes:
  ssh_keys:
    driver: local  
  rsync_logs:
    driver: local


secrets:
  rsync_config:
    file: /opt/bojemoi/volumes/rsync/configs/rsyncd.conf
  ssh_private_key:
    file: /opt/bojemoi/volumes/rsync/ssh-keys/id_rsa
  # =========================================================================
  # SERVICE:  rzync 
  # ========================================================================

# Template de base avec anchor
x-mode-template: &mode-template
  image: localhost:5000/koursk:latest
  networks:
    -  backend
  depends_on:
    - postgres
# Template de d..ploiement s..par..
x-deploy-template: &deploy-template
    placement:
      max_replicas_per_node: 1
    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
    update_config:
      parallelism: 1
      delay: 10s
      failure_action: rollback
    resources:
      limits:
        cpus: '0.1'
        memory: 512M
      reservations:
        cpus: '0.1'
        memory: 100M

services:
  rsync-master:
    <<: *mode-template  # H..rite du template de base
    image: localhost:5000/koursk-2:latest
    hostname: rsync-master
    ports:
       - "8080:8080"
    deploy:
      <<: *deploy-template  # H..rite du template de d..
      replicas: 1 
      placement:
        constraints:
          - node.role == manager
    volumes:
       - type: bind
         source: /opt/bojemoi
         target: /opt/bojemoi
       - ssh_keys:/root/.ssh:ro
       - rsync_logs:/var/log/rsync
    environment:
             - MODULE=swarm_data
             - DATA_PATH=/opt/bojemoi
             - RSYNC_MODE=master
             - SYNC_INTERVAL=300
             - REMOTE_HOSTS=rsync-slave
    networks:
       - rsync_network
    command: ["/scripts/rsync-start.sh"]



  rsync-slave:
    <<: *mode-template  # H..rite du template de base
    hostname: rsync-slave
    deploy:
      <<: *deploy-template  # H..rite du template de d..
      replicas: 3
      placement:
        preferences:
          - spread: node.id
      update_config:
        parallelism: 1
        delay: 10s
    volumes:
      - type: bind
        source: /opt/bojemoi
        target: /opt/bojemoi
      - ssh_keys:/root/.ssh
      - rsync_logs:/var/log/rsync
    environment:
      - RSYNC_MODE=slave
      - MASTER_HOST=rsync-master
      - DATA_PATH=/opt/bojemoi
    networks:
      - rsync_network
    command: ["/scripts/rsync-slave.sh"]


  rsync-monitor:
    image: localhost:5000/koursk-1:latest
    networks:
      -  backend
    depends_on:
    - postgres
    - loki
    - grafana
    - prometheus

    hostname: rsync-monitor
    deploy:
      <<: *deploy-template  # H..rite du template de d..
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - ALERT_EMAIL=admin@example.com
      - CHECK_INTERVAL=60
      - RSYNC_SERVICE_NAME=koursk
      - ROOT_SYNC_PATH=/opt/bojemoi
    networks:
      - rsync_network
      - monitoring
